export const ACTION_TYPE = {
 FILTER_NAVBAR: 'FILTER_NAVBAR',
 SELECT_FILTER_DATA: 'SELECT_FILTER_DATA',
 HIDE_AND_SHOW_NAV: 'HIDE_AND_SHOW_NAV',
 SET_CURRENT_USER: 'SET_CURRENT_USER',
 SET_DATA: 'SET_DATA',
};
